telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py", line 1982, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
